### PR TITLE
Update extract_monocular_cues.py

### PR DESCRIPTION
**Pull request by krahets**
The original code requires `/` at the end of `root_dir`.

### CODE REVIEW

**Review by LownyCGI — COMMENTED** [review]
It didn't help 
image

**Comment by joeylitalien** [comment]
> It didn't help image

@LownyCGI, by inspecting the code you will see that image filenames are required to end with `_rgb.png` (L179). You can remove this by setting it to `.png`, which should process all images accordingly.

**Comment by LownyCGI** [comment]
Ok. I'll check. Thank you 🫠21:10, 11 января 2023 г., Joey Litalien ***@***.***>:

It didn't help 

@LownyCGI, by inspecting the code you will see that image filenames are required to end with _rgb.png (L179). You can remove this by setting it to .png, which should process all images accordingly.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
//127.0.0.1

**Comment by LownyCGI** [comment]
Ok. I'll check thank you 🫠21:10, 11 января 2023 г., Joey Litalien ***@***.***>:

It didn't help 

@LownyCGI, by inspecting the code you will see that image filenames are required to end with _rgb.png (L179). You can remove this by setting it to .png, which should process all images accordingly.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
//127.0.0.1

**Review by niujinshuchong — APPROVED** [review]
thanks.

**Pull request merged**
