### PR TITLE
Polycam depth sensor

### PR DESCRIPTION
**Pull request by pablovela5620**
added sensor depth when available through polycam

### CODE REVIEW

**Comment by niujinshuchong** [comment]
Thanks for the PR. Could you share an example to show that it works as expected?

**Comment by pablovela5620** [comment]
Sure, heres a run I did with a custom polycam dataset
image
Mesh ended up a bit messy on the outskirts but I think this is because I didn't get up close to the walls and it was mostly empty space


https://user-images.githubusercontent.com/25287427/210100151-76eda4e8-152a-433f-bd46-5e51e63de833.mov

Let me know if you'd like the example dataset to try it yourself

**Comment by niujinshuchong** [comment]
Hi, thanks for sharing the results. It's the depth map in polycam already aligned with the RGB image? Or do we need additional calibration to align them? Your depth map looks very clean. Why doesn't it have missing depth in the border region like this?
image

**Comment by pablovela5620** [comment]
I believe it's because iPhone lidars do some postprocessing to the depth maps, more info can be found on what the exact format is [here](https://github.com/PolyCam/polyform), [here](https://developer.apple.com/documentation/arkit/arframe/3566299-scenedepth), and [here](https://developer.apple.com/documentation/avfoundation/additional_data_capture/capturing_depth_using_the_lidar_camera). I haven't worked much with metrically accurate depth maps (this is my first time with them given how easy they are to get from an iPhone with a lidar), but I think they are already aligned after modifying the camera intrinsics and interpolating/cropping the depth maps. (The original depth maps are significantly lower resolution 192x256)

Heres an example of the 384x384 image and depth map I get after preprocessing with the script
000403_rgb
000403_sensor_depth.

**Comment by niujinshuchong** [comment]
OK, thanks for the explanation.

**Review by niujinshuchong — APPROVED** [review]

**Pull request merged**
